### ISSUE TITLE
do not limit qcflags

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#10]
Hi,

The generic readers are hardcoded to block qcflags larger than 31. I don't think this is generic enough. Several satellite products have QC flags much larger than 31 (sparse like 1,2,4,6,31,256,2048) while others are more compact (1..10). 

I believe the only limiting factor here is to make sure they are integers.

See/discuss first commit in #11.

**Comment by sakov** [comment]
At this point this is a design feature. We may revisit it in the future if need occurs.
