### ISSUE TITLE
enable several qc flags to be set as good

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#12]
The current generic readers do not support several flags to be used as valid data in obs.prm

second commit in #11 add/fix support to:

```
parameter qcflags = 1, 2, 3, 4
```
to consider the flags as good ones.

**Comment by sakov** [comment]
Let me see.

The intention was to treat qcflag as a number from 0 to 31, and qcflagvals as a bitwise union of accepted flags (2^flag1 | 2^flag2 ... | d^flagN). I can see now that the current code has at least 2 defects implementing this:
1. After reading qcflag in reader_xy_gridded.c:287 there needs to be a check that 0 <= qcflag <= 31.
2. On l. 342 it needs be if (qcflag != NULL && !(1 << qcflag[i] & qcflagvals))

Now, it seems that by removing restriction 0 <= qcflag <= 31 you have a different concept in mind. Could you describe it.

**Comment by ocehugo** [comment]
The proposed changes were first designed to enable several flags to be marked as valid:

```
parameter qcflags = 1, 2, 3
```

This was not possible with the logic in HEAD, so I had to change to the one proposed 1<<qcflag[i]. 


> Now, it seems that by removing restriction 0 <= qcflag <= 31 you have a different concept in mind. Could you describe it. Also note that if qcflag is outside this range then one can not sensibly use "1<<qcflag[i]" as you propose.

You are correct. When removing the bound check, I'm introducing another bug where other flags in the 31<x<N middle are accepted, as well as the selected ones.
Clearly, I didn't think on the precision bounds after removing the range constraint. Unfortunately, this appeareda s a first commit because I rebase that hunk first (it was the last modification in my fork).

I will remove the binary logic and check the flags with a loop within the array. This way several flags without bounds can be used.
