### ISSUE TITLE
BUG: wrong logic on estd/std/error_std in generic readers

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#13]
The current logic on estd for the generic reader is incomplete:

1. If the user did not provide an estd variable (```parameter estdname``` is missing)
2. but provide an std variable (```parameter stdname = VARSTD```)
3. The code completely miss setting o->std with the proper values in stdname. *EDITED*

See line 361 onwards in reader_xy_gridded.c for example.

The third commit in #11 fix this issue by checking if both std/estd where not provided, before setting the std and keep going.
The check inside is pedantic on purpose ( the nan check), given that I don't know if you want to set a precedence order in the case the user provided all three std parameters (estd/std/ and/or error_std attribute).

The last commit in #11 fix a segfault case where estd[i] is accessed when not defined because the change in logic above.

**Comment by sakov** [comment]
Hugo, I still can not see what is wrong with the current code -- could you give an example when it works incorrectly.

Note that "std" is the internal variability of the collated data (see the header of reader_xy_gridded.c), while "o->std" is the observation error standard deviation.

The current code works as follows.
1. If both "std" and "estd" are specified, then the greater one is used for the observation error.
2. If "estd" is not specified, observation error is set to NaN. It then has to be set explicitly in obs.prm.

**Comment by ocehugo** [comment]
Hi Pavel,

> Note that "std" is the internal variability of the collated data (see the header of reader_xy_gridded.c), while "o->std" is the observation error standard deviation.
>The current code works as follows.
>
>If both "std" and "estd" are specified, then the greater one is used for the observation error.
If "estd" is not specified, observation error is set to NaN. It then has to be set explicitly in obs.prm.

Yes, I understand that.

I changed the code because there is no rule for:

3. The user provides only "std".

I would expect that, if the user provides only the standard deviation of the collated data, this would be the observation error *at the end of the reader*. 

*at the end of the reader* because the user can still provide the "error_std" in the obs.prm, that is not set in the reader but later in prep_utils. This way it can go forward with an "observation error" that is a mix of them.

Scenario:
```obs.prm
...
parameter varname =  X
parameter stdname = X_std
error_std = 0.1
...
```

using HEAD, with the above scenario:  
1. estd == NULL (initialized and unchanged)
2. var_estd == NaN (initialized and unchanged since std != NULL).
3. Then o->std is set to NaN/var_estd (line 361). 
(as you described).

However:
4. The obs *raw collated variability* is discarded.
5. The code afterwards is supposedly to change the error according to the user option (EQ,MIN,MAX,etc) in prep_utils.c, missing entirely the "std" provided.


I could provide the "std" as "estd" but this is semantically wrong, although in practice would achieve the desired result. 

The propose changes just enable this case to be semantically correct (say for HF-Radar the error estimate is the standard deviation of averaged data in a time window/box area).

**Comment by ocehugo** [comment]
> No, this would be wrong. In many cases (say, if there is only one point collated) std = 0. In many other cases it will be much less than the assumed observation error. In these cases (of 0 or very small "std") using it in DA for observation error would be a disaster.

I disagree. You are considering/viewing from above the reader scope (and I agree with you if viewed from atop). 
I'm not changing definitions, not talking about superobing, and definitely not setting so->std or so->var (what matters), but obs->std **at the end of the reader** for each **raw** obs.

In fact, this is all about changing ```obs->std = NaN``` to ```obs->std = stdname```, in the case the user provide **only** stdname.


> You are right that if the observation error is not set in the observation data file, then (as coded) the internal variability of the collated data is not used. But
(1) This is not a big issue, as considering or not the internal variability is rarely important.
(2) One can hardly expect to meet a situation when the observation error is not specified in the data file, but the internal variability is.
(3) Should this situation occur, it can be easily handled by adding parameter "error_std" for the data variable in the data file.

The internal variability of the **raw** observations is only taken into account if both std and estd are provided. 

(1) Disagree. Why prep should abort (obs->std=NaN) if I provide an error estimate in the form of internal variability and nothing else? The standard user behaviour in this case is to change stdname to estdname anyway...I'm just avoiding that.

(2) Semantically, this is the case of hourly HF-Radar estimates. The only error estimate provided is an internal variability over an hour at a point. In a practical sense, this is both the internal variability and/or the observational error of the raw obs. The user may want to increase that (as 3), but the the collated internal variability of the superobs will be grid and parameter dependent anyway (subgrid/across-instrument/etc).

(3) Agree, and it's important in any case as a  hack/leverage for the error.

You are upstream, so I will follow whenever I can :).

At the end of the day, I just thought that, under the scenario above,  it was better to read the stdname variable and use it instead of setting obs->std to NaN.
