### ISSUE TITLE
Question: why reading superobs again and removing land obs after writing?

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#16]
Hi Pavel,

I'm wondering about the writing/reading/writing scheme in enkf_prep.c.

Why prep has to re-read the superobservations file and discard the sobs structure that was just used to write the superobs file?
Also, why the obs_checkforland has to be run after writing and not before?

Finally, shouldn't the write of sobs file be postponed to be after land checking and avoid write/read/write thing? I did some changes to "write" at the end only, and the observations.nc are unchanged for my tests. I'm wondering if this write/read/write is some "cleanup" on the sobs structure or just a remnant of testing...

```
    if (do_superob) {
        enkf_printf("  superobing:\n");
        obs_superob(obs, cmp_obs, &sobs, describe_superob_id);

        if (describe_superob_id >= 0)
            goto finalise;

        enkf_printf("  writing superobservations to \"%s\":\n", FNAME_SOBS);
        obs_write(sobs, FNAME_SOBS);
        // WHY!?
        free(sobs->data);
        enkf_printf("  reading super-observations from disk:\n");
        obs_read(sobs, FNAME_SOBS);

        enkf_printf("  checking for superobs on land:\n");
        if (obs_checkforland(sobs, m)) {
            obs_compact(sobs);
            for (i = 0; i < sobs->nobs; ++i)
                if (sobs->data[i].status != STATUS_OK)
                    break;
            assert(i != sobs->nobs);
            enkf_printf("    deleted %d observations\n", sobs->nobs - i);
            sobs->nobs = i;
            //WHY bother!?
            file_delete(FNAME_SOBS);
            enkf_printf("  writing good superobservations to \"%s\":\n", FNAME_SOBS);
            //move outside the if?
            obs_write(sobs, FNAME_SOBS);
        } else
            enkf_printf("    all good\n");
    } else {
        observation* data = malloc(obs->ngood * sizeof(observation));

        memcpy(data, obs->data, obs->ngood * sizeof(observation));
        sobs = obs_create_fromdata(obs, obs->ngood, data);
        obs_write(sobs, FNAME_SOBS);
        goto finalise;
    }
```

**Comment by sakov** [comment]
Because writing "double" values to disk as "float" and then reading back results in minor numerical difference. Very rarely this moves an observation from a water cell to a land cell and results in failures in CALC. I guess we need to change all "double" fields in struct observations to "float", for starters. I do not hurry with this because, firstly, the current way around works well enough, and secondly, not 100% sure whether writing and reading a float from e NetCDF file can be guaranteed to result in a numerically identical value.
