### ISSUE TITLE
dir_rmifexists fails if directory is not empty

### ISSUE THREAD

**Issue by ColemanTom** [sakov/enkf-c#18]
Hi @sakov,

The function dir_rmifexists fails if the directory is not empty. The use of `rmdir` in https://github.com/sakov/enkf-c/blob/master/enkf/common/utils.c#L619 only works if it's an empty directory.

I have seen this impact one of our jobs that got killed in a non-clean manner such that the DIRNAME_TMP is not cleaned up. I have pasted the output below from an attempt to rerun after this event.

I think you need something like https://stackoverflow.com/questions/5467725/how-to-delete-a-directory-and-its-contents-in-posix-c/5467788#5467788 to handle recursive deletion instead.

```
  ERROR: enkf: CPU #0: could not remove directory ".enkftmp": Directory not empty


  I am CPU #0, now printing the backtrace:

  obtained 5 stack frames:
[0x45173d]
[0x44e824]
[0x43315a]
[0x325bc51]
[0x4081a1]
```

**Comment by sakov** [comment]
Hi Tom,

This is done purposely -- not to allow to start a job in the EnKF work directory if there is (a chance of) another/previous job running. (See CHANGELOG on v2.9.7 and 2.9.10.) If the previous job has crashed .enkftmp has to be removed before re-running.

Cheers.
Pavel
