### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by nikhil003** [sakov/enkf-c#2]
Hi,

I have been trying to compile enkf library, but i keep on getting this error

common/observations.c:878:37: error: unknown type name '__compar_d_fn_t'
void obs_superob(observations* obs, __compar_d_fn_t cmp_obs, observations** sobs, int sobid)

I think it is an incompatibility issue between mac and linux. I can compile the rest of files by commenting out  "__compar_d_fn_t" usage. Also, when i compile, the qsort-r gets called from stdlib, but i think i still need to have way around this as this is used by super-orb part of this library

i would appreciate any help with this.

**Comment by sakov** [comment]
Hi, try adding compiler flag -DINTERNAL_QSORT_R (user manual, p. 39)
-Pavel

**Comment by nikhil003** [comment]
Hi, 

i don't think it is an error because of qsort_r algorithm. I have used as the compiler flag as per your suggestion and it is still giving me the same error.

```In file included from prep/prep_utils.c:31:0:
./common/observations.h:118:37: error: unknown type name '__compar_d_fn_t'
 void obs_superob(observations* obs, __compar_d_fn_t cmp_obs, observations** sobs, int sobid);
                                     ^~~~~~~~~~~~~~~
In file included from common/observations.c:27:0:
common/observations.h:118:37: error: unknown type name '__compar_d_fn_t'
 void obs_superob(observations* obs, __compar_d_fn_t cmp_obs, observations** sobs, int sobid);
                                     ^~~~~~~~~~~~~~~
common/observations.c:878:37: error: unknown type name '__compar_d_fn_t'
 void obs_superob(observations* obs, __compar_d_fn_t cmp_obs, observations** sobs, int sobid)
                                     ^~~~~~~~~~~~~~~
In file included from prep/allreaders.c:27:0:
./common/observations.h:118:37: error: unknown type name '__compar_d_fn_t'
 void obs_superob(observations* obs, __compar_d_fn_t cmp_obs, observations** sobs, int sobid);
                                     ^~~~~~~~~~~~~~~
```

**Comment by sakov** [comment]
Hi Nikhil,

The error occurs when compiling observations.c.

__compar_d_fn_t is defined in utils.h.

utils.h is included in observations.c before observations.h, which triggers
the error.

So... __compar_d_fn_t is defined if there is compiler flag
-DINTERNAL_QSORT_R.

But you are saying you have added -DINTERNAL_QSORT_R to the compiler flags.
To make sure -- could you send me the full output of "make" command?

Best regards,
Pavel

**Comment by nikhil003** [comment]
Hi,

I have figured it out. I realized that the internal qsort_r had a conflict with qsort_r from stdlib.h, 
so i did a renamed qsort_r to _qsort_r, and now it worked.

i didnt remove stdlib.h, as it contains "malloc" on mac
