### ISSUE TITLE
Enable ENKF input files as arguments!?

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#4]
Hi,

I think It would be good to be able to specify all input files as arguments:

```
enkf_prep -i enoi.prm -obstype obstype.prm -obs obs.prm -grid grid.prm
```

This would enable code tests to be easily implemented and executed, such as in the makefile. This would also help identify bugs and test invalid user requests.

This led me to think on why not put *almost* everything in one single file!? maybe I'm missing something, but except for the obs.prm, I cannot foresee advantage of several input files. It would help a lot for testing too by simplifying the call and case writing.

Moreover, in a single file, changing parameters would be 1. easy with cat/sed/awk/etc, 2.help to maintain a consistent experiment when copying around, 3. running different parameter cases would be easier, and 4. organization would be better.

In any case, people out there are using generators of the prm files. This would only simplify their life, by including a single generator of one (bigger) input file (as well as the obs.prm).

**Comment by sakov** [comment]
We have put quite a bit of thought into how the parameter files are structured, and after using the code for 6 years are quite happy with the current parameter file framework. I consider it unlikely to  change much in future.
