### ISSUE TITLE
Vertical superobing in sigma coordinates wrong!?

### ISSUE THREAD

**Issue by ocehugo** [sakov/enkf-c#6]
Hi pavel,

Apparently, the current HEAD code is superobing at the wrong positions in the vertical. This appears similar to #5.

Looks like cell centres for *sigma* type coordinates are assumed as cell-edges:

![enkfc_wrong_vertical_superobs](https://user-images.githubusercontent.com/1202691/42195323-ad5445b2-7ebb-11e8-9fb1-c3d059a2dcfd.png)

The above show clearly that enkf_prep is superobing something that should not be averaged, given obs lie within the cell edges (black lines). Looks like an offset like in the one done in #5 is required. Not sure about other coordinates, but likely the case too.

Observations are from a fake z profile using the cars readers. All depths were calculated with the roms equations for Vt=2,Vs=4,theta_s=7,theta_b=0.5,hc=200. Local depth is 4883.527.

I will tear down an example if required.

**Comment by sakov** [comment]
Firstly, even if superobservation cells were centered at cell corners, there would be no drama with that (DA-wise). It would be just not how it is supposed to be.

Secondly, after checking the code, and checking modified example 1 (with 4 layers), I can not observe the problem. I believe that in the above plot the layer corners are actually shown in red, layer centres in black, and everything is fine.

I am going to close this issue unless it is reported in a reproduceable way.

**Comment by ocehugo** [comment]
Hi,

I understand the scepticism, but no, the plot is correct (red is centre/black is edge).

As requested, a figure from example 1 using cars reader: 

![eac_error](https://user-images.githubusercontent.com/1202691/42253566-a871e584-7f85-11e8-8ec4-a9bb1d2f3261.png)

Surprisingly, this is also incorrect. The red dashed lines are the t-cell positions -- variable zt in grid_spec (not the centre of the cell, but somewhere away from the edges). It's also incorrect. Let me know if I did something wrong for this case.

Files can be obtained here: https://s3-ap-southeast-2.amazonaws.com/ekmanpublicbucket/enkf-c-tests/eac_test_cars_fakez.tar.gz

**Comment by sakov** [comment]
In example 1 the cell centres are at zt = {2.5, 255.9}, accordingly the
cell corners are at zc = {0, 5, 506.8}. In the plot above the observations
in the depth interval [5, 506.8] are collated into a superob at about 300.
What is the problem?

**Comment by ocehugo** [comment]
You are correct, my fault. Sorry, I got a typo when defining the vars :) .  You can close the issue.
